> Isikan identitas berikut :

- NIM   : 2241727017
- Nama  : Irfan Purwo Saputro
- Kelas : TI-4J

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
mus = pd.read_csv('mushrooms.csv')
mus.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [3]:
y = mus['class']
y = y.map({'p':1, 'e':0})
X1 = mus['cap-shape'].map({'x':0, 'b':1, 's':2, 'f':3,'k':4,'c':5})
X2 = mus['bruises'].map({'t':0, 'f':1})

v1=[]
v2=[]
for x1 in X1:
  v1.append(x1)
for x2 in X2:
  v2.append(x2)

X = pd.DataFrame()

X['cap-shape'] = v1
X['bruises'] = v2
print(X)

      cap-shape  bruises
0             0        0
1             0        0
2             1        0
3             0        0
4             0        1
...         ...      ...
8119          4        1
8120          0        1
8121          3        1
8122          4        1
8123          0        1

[8124 rows x 2 columns]

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [5]:
from sklearn.tree import DecisionTreeClassifier

# Instantiate DecisionTreeClassifier 'dt' dengan kedalaman maksimum 6
dt = DecisionTreeClassifier(max_depth=6, random_state=1)

# Sesuaikan dt ke set training
dt.fit(X_train, y_train)

# Pmemprediksi label set test
y_pred = dt.predict(X_test)
print(y_pred[0:5])

[1 1 1 1 0]

In [6]:
from sklearn.metrics import accuracy_score

# Memprediksi test set labels
y_pred = dt.predict(X_test)

#  menghitung set accuracy
acc = accuracy_score(y_test, y_pred)
print("Test set accuracy: {:.2f}".format(acc))

Test set accuracy: 0.78